[project]
name = "everybody-codes"
version = "0.1.0"
description = "Python solutions for the Everybody Codes challenges"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
]
